# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9633941220b57b05dc65e440a83df4193b9ebb942557b713e6852b1d90a67769b06dcf69a6896b1eef9c48f69ea494fb00d52e22da64a57bda282f766ff898f3

test:
  secret_key_base: 103cd46f1391b63fe2755b22ea8b705eb75d7942efd34151fa825ea421edf9c6faf8e8ab73f8893c9618db1077da43ed45d4e07b4672bdd1dfd528df524155ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
